### ISSUE TITLE
Random Choice

### ISSUE THREAD

**Issue by DaLiteralPanda** [DaLiteralPanda/Pandomiser#14]
Add the option to choose a random choice between the values given (so you could work with strings for example `p!randomChoice hi heya hey`

**Comment by LucAngevare** [comment]
Remember, this means a random choice between given values, not the random range command (I got confused when reading this)
This is actually somewhat fairly simple to implement as you can just do

```
const valueArr = message.replace(`${prefix}randomChoice `, "").split(" ")
const randomVal = valueArr[Math.floor(Math.random() * valueArr.length)]
message.channel.say(`${randomVal}, I choose you!`)
```

Off the top of my head, didn't actually test this.
