### ISSUE TITLE
Add actual quotes and change the command of the Markov quotes

### ISSUE THREAD

**Issue by LucAngevare** [DaLiteralPanda/Pandomiser#27]
The quotes currently are wildly fake and usually don't make sense, why not make a separate command for actual quotes so people don't get confused when they get a quote that doesn't make sense and doesn't have an author. If I remember correctly I still have a good quote dataset in JSON format so I'll make a pull request for this myself.

**Comment by iddev5** [comment]
Instead of doing a command for real quotes, why not replace the current one to give real quotes and then add a new command for fake quotes.

This is because: ``randomFakeQuote`` makes sense whereas ``randomRealQuote`` doesn't.

**Comment by LucAngevare** [comment]
That's a really good suggestion, I'll change the current quote command to randomFakeQuote and make randomQuote give real quotes, I'll work on that whenever I have enough time
